services:
  vcf-app:
    build: .
    container_name: vcf-bot
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./storage/uploads:/app/storage/uploads
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
